### ISSUE TITLE
Behavior changed? Gets removed every rebuild.

### ISSUE THREAD

**Issue by fritx** [johnagan/clean-webpack-plugin#31]
Hello there,
I've been used this module since Jan or Feb, 2016. (v0.1.4-v0.1.10)
Recently I re-installed this module (updated), and things changed.

Dist directory gets removed after every single rebuild.
My expected behavior was to clean just at the first time.
I couldn't find any documentation.

**Comment by johnagan** [comment]
See #29 - Sorry for the trouble @fritx

**Comment by eladnava** [comment]
According to https://github.com/johnagan/clean-webpack-plugin/issues/29#issuecomment-253644912, this bug has not been fixed unfortunately. 

Please reopen this issue. 👍

**Comment by tylerhou** [comment]
@eladnava This bug has been fixed in the latest version (which was a rollback of my original pull request), so it should remain closed.

**Comment by eladnava** [comment]
@tylerhou I'm still experiencing a full directory deletion instead of just the files inside with the latest version, using this code:

```
plugins: [
        new CleanWebpackPlugin(['build'])
]
```

**Comment by scott-thrillist** [comment]
Same issue as @eladnava

**Comment by tylerhou** [comment]
So this issue specifically is about deletion on watch. That is, if you were running `webpack --watch`, you would have seen the directories be deleted every single time you changed your code and webpack recompiled. That was an undocumented change (my apologies) and has been fixed with the rollback.

On the other hand, full directory deletion is intentional. If you want to delete files inside the directory, you'll have to specify them individually. For most users the difference between deletion of a directory and deletion of all the files inside a directory but not the directory itself is negligible, since usually webpack would immediately recreate it on compile.
